import type { CaseBundle } from "@/lib/types";

export const demoCase: CaseBundle = {
  caseRecord: {
    id: "demo-child-a",
    label: "Case A-17",
    disease: "Sanfilippo Syndrome Type A",
    therapy: "UX111 observational evidence brief",
    observationStart: "2024-03-08",
    observationEnd: "2026-02-11",
    reviewWindow: "FDA resubmission accepted April 2, 2026. PDUFA date September 19, 2026.",
    summary:
      "A de-identified observational case assembled from caregiver-style fragments to demonstrate how lived experience can surface functional stability signals over time.",
    dataHandling:
      "Demo records are synthetic or de-identified and rendered locally to avoid restricted-data handling in the hackathon build.",
  },
  fragments: [
    {
      id: "FRG-2024-031",
      caseId: "demo-child-a",
      date: "2024-03-08",
      sourceType: "Parent Journal",
      modality: "text",
      title: "Breakfast naming routine",
      excerpt:
        "Identified spoon, bowl, dog, and juice without prompting. Needed one cue for sister's name.",
      tags: ["vocabulary", "objects", "family"],
      signalDomain: "vocabulary",
      deidentified: true,
      confidence: "high",
      rawRef: "Journal / March 2024 / Entry 03",
    },
    {
      id: "FRG-2024-067",
      caseId: "demo-child-a",
      date: "2024-05-18",
      sourceType: "Voice Memo",
      modality: "audio-transcript",
      title: "Playroom voice memo",
      excerpt:
        "Transcript records spontaneous use of four animal words and one two-word phrase during floor play.",
      tags: ["vocabulary", "play", "phrase length"],
      signalDomain: "vocabulary",
      deidentified: true,
      confidence: "moderate",
      rawRef: "Voice memo transcript / May 2024",
    },
    {
      id: "FRG-2024-114",
      caseId: "demo-child-a",
      date: "2024-08-03",
      sourceType: "Clinic Summary",
      modality: "summary",
      title: "Neurodevelopment follow-up",
      excerpt:
        "Family reports recognition of primary caregivers remains intact. Child initiates eye contact and responds to own nickname consistently.",
      tags: ["recognition", "caregiver", "social"],
      signalDomain: "recognition",
      deidentified: true,
      confidence: "high",
      rawRef: "Clinic summary / August 2024",
    },
    {
      id: "FRG-2024-162",
      caseId: "demo-child-a",
      date: "2024-11-27",
      sourceType: "Forum Observation",
      modality: "text",
      title: "Sleep pattern update",
      excerpt:
        "Caregiver notes that full-night sleep now happens three nights per week instead of one.",
      tags: ["sleep", "night waking", "routine"],
      signalDomain: "sleep",
      deidentified: true,
      confidence: "moderate",
      rawRef: "Forum paraphrase / November 2024",
    },
    {
      id: "FRG-2025-018",
      caseId: "demo-child-a",
      date: "2025-01-20",
      sourceType: "Parent Journal",
      modality: "text",
      title: "Name recall after weekend visit",
      excerpt:
        "Recognized grandmother immediately and said her nickname before being prompted.",
      tags: ["recognition", "family", "memory"],
      signalDomain: "recognition",
      deidentified: true,
      confidence: "high",
      rawRef: "Journal / January 2025 / Entry 05",
    },
    {
      id: "FRG-2025-051",
      caseId: "demo-child-a",
      date: "2025-03-14",
      sourceType: "Caregiver Transcript",
      modality: "audio-transcript",
      title: "Bedtime conversation transcript",
      excerpt:
        "Transcript shows retained use of core bedtime words: blanket, moon, book, mama, and done.",
      tags: ["vocabulary", "bedtime", "retained lexicon"],
      signalDomain: "vocabulary",
      deidentified: true,
      confidence: "high",
      rawRef: "Transcript / March 2025 / Segment 11",
    },
    {
      id: "FRG-2025-093",
      caseId: "demo-child-a",
      date: "2025-06-02",
      sourceType: "Clinic Summary",
      modality: "summary",
      title: "Behavioral snapshot",
      excerpt:
        "Irritability is present but family reports a stable calming routine and fewer prolonged overnight episodes.",
      tags: ["behavior", "sleep", "routine"],
      signalDomain: "behavior",
      deidentified: true,
      confidence: "moderate",
      rawRef: "Clinic summary / June 2025",
    },
    {
      id: "FRG-2025-128",
      caseId: "demo-child-a",
      date: "2025-08-19",
      sourceType: "Parent Journal",
      modality: "text",
      title: "Meal-time object use",
      excerpt:
        "Still reaches for spoon and cup correctly. Needed extra help with fork sequencing but recognizes both objects by name.",
      tags: ["vocabulary", "motor", "objects"],
      signalDomain: "motor",
      deidentified: true,
      confidence: "moderate",
      rawRef: "Journal / August 2025 / Entry 22",
    },
    {
      id: "FRG-2025-171",
      caseId: "demo-child-a",
      date: "2025-11-06",
      sourceType: "Voice Memo",
      modality: "audio-transcript",
      title: "Morning greeting clip",
      excerpt:
        "Transcript captures correct greeting of father and repetition of dog, car, and outside during morning routine.",
      tags: ["vocabulary", "recognition", "daily routine"],
      signalDomain: "recognition",
      deidentified: true,
      confidence: "moderate",
      rawRef: "Voice memo transcript / November 2025",
    },
    {
      id: "FRG-2026-013",
      caseId: "demo-child-a",
      date: "2026-01-12",
      sourceType: "Clinic Summary",
      modality: "summary",
      title: "Winter clinic review",
      excerpt:
        "Caregiver continues to report preserved recognition of primary family members and stable response to favorite songs.",
      tags: ["recognition", "music", "caregiver"],
      signalDomain: "recognition",
      deidentified: true,
      confidence: "high",
      rawRef: "Clinic summary / January 2026",
    },
    {
      id: "FRG-2026-024",
      caseId: "demo-child-a",
      date: "2026-01-28",
      sourceType: "Caregiver Transcript",
      modality: "audio-transcript",
      title: "Kitchen transcript",
      excerpt:
        "Used six familiar nouns across a five-minute transcript with no observed reduction from last spring's home recordings.",
      tags: ["vocabulary", "noun count", "comparison"],
      signalDomain: "vocabulary",
      deidentified: true,
      confidence: "high",
      rawRef: "Transcript / January 2026 / Segment 02",
    },
    {
      id: "FRG-2026-039",
      caseId: "demo-child-a",
      date: "2026-02-11",
      sourceType: "Forum Observation",
      modality: "text",
      title: "Night routine post",
      excerpt:
        "Reported two consecutive weeks with only brief waking and faster return to sleep after reassurance.",
      tags: ["sleep", "night waking", "stability"],
      signalDomain: "sleep",
      deidentified: true,
      confidence: "moderate",
      rawRef: "Forum paraphrase / February 2026",
    },
    {
      id: "FRG-2026-041",
      caseId: "demo-child-a",
      date: "2026-02-11",
      sourceType: "Parent Journal",
      modality: "text",
      title: "Recognition check during visit",
      excerpt:
        "Turned toward aunt's voice immediately and smiled when favorite stuffed dog was named.",
      tags: ["recognition", "voice", "objects"],
      signalDomain: "recognition",
      deidentified: true,
      confidence: "high",
      rawRef: "Journal / February 2026 / Entry 04",
    }
  ],
  claims: [
    {
      id: "CLM-VOCAB-STABLE",
      caseId: "demo-child-a",
      statement:
        "Expressive vocabulary appears preserved across the 2024 to early 2026 observation window, with repeated use of familiar nouns and short phrases in home settings.",
      domain: "vocabulary",
      trend: "stable",
      confidence: "high",
      fragmentIds: ["FRG-2024-031", "FRG-2024-067", "FRG-2025-051", "FRG-2026-024"],
    },
    {
      id: "CLM-RECOGNITION-STABLE",
      caseId: "demo-child-a",
      statement:
        "Recognition of primary caregivers and familiar voices remains intact across clinic and home evidence sources.",
      domain: "recognition",
      trend: "stable",
      confidence: "high",
      fragmentIds: ["FRG-2024-114", "FRG-2025-018", "FRG-2026-013", "FRG-2026-041"],
    },
    {
      id: "CLM-SLEEP-IMPROVING",
      caseId: "demo-child-a",
      statement:
        "Sleep disruption remains present but caregiver reports suggest improvement in full-night sleep and faster return to sleep after waking.",
      domain: "sleep",
      trend: "improving",
      confidence: "moderate",
      fragmentIds: ["FRG-2024-162", "FRG-2025-093", "FRG-2026-039"],
    }
  ],
};
